//----------------
//  UI Definitions
//----------------


#define MAX_SPRITES   	768
#define TOP_SCREEN_WIDTH  	400
#define TOP_SCREEN_HEIGHT 	240
#define BOT_SCREEN_WIDTH	320
#define BOT_SCREEN_HEIGHT	240
#define TOP_UISPRITECOUNT 	15  //Max sprites that will be loaded for the top
#define BOT_UISPRITECOUNT	27   //Max sprites that will be loaded for the bottom

#define BOT_SCREEN 		0
#define TOP_SCREEN 		1

#define COLOUR_C32_WHITE    C2D_Color32(255,255,255,255)
#define COLOUR_C32_BLACK    C2D_Color32(0,0,0,255)

//Background Colour RGBA
#define BGCOLOUR_R 		42
#define BGCOLOUR_G		157
#define BGCOLOUR_B		205
#define BGCOLOUR_A		255

//Parameters for drawing the top screen's top bar rectangle
#define TOP_TOPBARCOLOUR_R	9
#define TOP_TOPBARCOLOUR_G	73
#define TOP_TOPBARCOLOUR_B	219
#define TOP_TOPBARCOLOUR_A	255
#define TOP_TOPBARCOORD_X	0
#define TOP_TOPBARCOORD_Y	0
#define TOP_TOPBARCOORD_Z	0
#define TOP_TOPBARHEIGHT	28	

//Parameters for drawing the top screen's top bar rectangle
#define BOT_TOPBARCOLOUR_R	9
#define BOT_TOPBARCOLOUR_G	73
#define BOT_TOPBARCOLOUR_B	219
#define BOT_TOPBARCOLOUR_A	255
#define BOT_TOPBARCOORD_X	0
#define BOT_TOPBARCOORD_Y	0
#define BOT_TOPBARCOORD_Z	0
#define BOT_TOPBARHEIGHT	28

//Grey out tint defines

#define GREY_OUT_TINT 0.6

//BOTTOM SCREEN
// Tab state


#define BOT_TAB_STATE_CONNECTION    0
#define BOT_TAB_STATE_CONTROLVALUES 1
#define BOT_TAB_STATE_CONFIG        2

#define BOT_TAB_STATE_MAX BOT_TAB_STATE_CONFIG

//Tab sprite definitions definition

#define BOT_TAB_ANIM_Y  -4

#define BOT_TAB_CONN_X  31
#define BOT_TAB_CONN_Y  18
#define BOT_TAB_CONN_TOUCH_X	(BOT_TAB_CONN_X-(BOT_TAB_CONN_SIZE_X / 2)) //Calculate top corner from the centre of the sprite
#define BOT_TAB_CONN_TOUCH_Y	(BOT_TAB_CONN_Y-(BOT_TAB_CONN_SIZE_Y / 2))
#define BOT_TAB_CONN_SIZE_X	    54
#define BOT_TAB_CONN_SIZE_Y	    22

#define BOT_TAB_CONTROLS_X  (BOT_TAB_CONN_X + BOT_TAB_CONTROLS_SIZE_X + 4) //X is the position of the tab to the left + sprite width + gap
#define BOT_TAB_CONTROLS_Y  BOT_TAB_CONN_Y
#define BOT_TAB_CONTROLS_TOUCH_X	(BOT_TAB_CONTROLS_X-(BOT_TAB_CONTROLS_SIZE_X / 2))
#define BOT_TAB_CONTROLS_TOUCH_Y	(BOT_TAB_CONTROLS_Y-(BOT_TAB_CONTROLS_SIZE_Y / 2))
#define BOT_TAB_CONTROLS_SIZE_X	    54
#define BOT_TAB_CONTROLS_SIZE_Y	    22

#define BOT_TAB_CONFIG_X  (BOT_TAB_CONTROLS_X + BOT_TAB_CONFIG_SIZE_X + 4) //X is the position of the tab to the left + sprite width + gap
#define BOT_TAB_CONFIG_Y  BOT_TAB_CONN_Y
#define BOT_TAB_CONFIG_TOUCH_X	(BOT_TAB_CONFIG_X-(BOT_TAB_CONFIG_SIZE_X / 2))
#define BOT_TAB_CONFIG_TOUCH_Y	(BOT_TAB_CONFIG_Y-(BOT_TAB_CONFIG_SIZE_Y / 2))
#define BOT_TAB_CONFIG_SIZE_X	    54
#define BOT_TAB_CONFIG_SIZE_Y	    22


// CONNECTION SCREEN 
// Connection Screen console

#define CON_SCR_CONSCOLOUR_R	64
#define CON_SCR_CONSCOLOUR_G	64
#define CON_SCR_CONSCOLOUR_B	64
#define CON_SCR_CONSCOLOUR_A	255
#define CON_SCR_CONSCOORD_X		32
#define CON_SCR_CONSCOORD_Y		68
#define CON_SCR_CONSCOORD_Z		0
#define CON_SCR_CONSWIDTH		256
#define CON_SCR_CONSHEIGHT		160	

#define CON_SCR_TEXT_X			35
#define CON_SCR_TEXT_Y			72
#define CON_SCR_MAX_NL_CHAR		10

char connConsoleString[256] = "";

//Connection screen buttons

#define CON_SCR_BUT_CONNECT_X	        52
#define CON_SCR_BUT_CONNECT_Y	        48
#define CON_SCR_BUT_CONNECT_TOUCH_X	    11
#define CON_SCR_BUT_CONNECT_TOUCH_Y	    37
#define CON_SCR_BUT_CONNECT_SIZE_X	    82
#define CON_SCR_BUT_CONNECT_SIZE_Y	    22

#define CON_SCR_BUT_DISCONNECT_X	        160
#define CON_SCR_BUT_DISCONNECT_Y	        CON_SCR_BUT_CONNECT_Y
#define CON_SCR_BUT_DISCONNECT_TOUCH_X	    109
#define CON_SCR_BUT_DISCONNECT_TOUCH_Y	    37
#define CON_SCR_BUT_DISCONNECT_SIZE_X	    103
#define CON_SCR_BUT_DISCONNECT_SIZE_Y	    22

#define CON_SCR_BUT_IPADDR_X            (BOT_SCREEN_WIDTH - CON_SCR_BUT_CONNECT_X)
#define CON_SCR_BUT_IPADDR_Y            CON_SCR_BUT_CONNECT_Y

#define CON_SCR_BUT_IPADDR_TOUCH_X	    (CON_SCR_BUT_IPADDR_X-(CON_SCR_BUT_IPADDR_SIZE_X / 2))
#define CON_SCR_BUT_IPADDR_TOUCH_Y	    (CON_SCR_BUT_IPADDR_Y-(CON_SCR_BUT_IPADDR_SIZE_Y / 2))
#define CON_SCR_BUT_IPADDR_SIZE_X	        82
#define CON_SCR_BUT_IPADDR_SIZE_Y	        22

//-------------


//CV Screen

//Coverbar
#define CV_SCR_COVER_BARCOLOUR_R	BGCOLOUR_R
#define CV_SCR_COVER_BARCOLOUR_G	BGCOLOUR_G
#define CV_SCR_COVER_BARCOLOUR_B	BGCOLOUR_B
#define CV_SCR_COVER_BARCOLOUR_A	255
#define CV_SCR_COVER_BARCOORD_X	    0
#define CV_SCR_COVER_BARCOORD_Y	BOT_TOPBARHEIGHT
#define CV_SCR_COVER_BARCOORD_Z	    0
#define CV_SCR_COVER_BARHEIGHT	    40

#define CV_SCR_LIST_SPIRTE_X        (BOT_SCREEN_WIDTH/2)
#define CV_SCR_LIST_SPIRTE_BASE_Y   ((BOT_SCREEN_HEIGHT + (CV_SCR_LIST_SPIRTE_SIZE_Y/2))+ CV_SCR_LIST_SPIRTE_SIZE_Y)
#define CV_SCR_LIST_SPIRTE_SIZE_X   304
#define CV_SCR_LIST_SPIRTE_SIZE_Y   32
#define CV_SCR_LIST_SPIRTE_SPACING  (CV_SCR_LIST_SPIRTE_SIZE_Y + 2)
#define CV_SCR_LIST_TEXT_X          (CV_SCR_LIST_SPIRTE_X - (CV_SCR_LIST_SPIRTE_SIZE_X / 2 ) + 15 )

int CV_SCR_LIST_SPIRTE_Y = ((BOT_SCREEN_HEIGHT + (CV_SCR_LIST_SPIRTE_SIZE_Y/2))+ CV_SCR_LIST_SPIRTE_SIZE_Y);

#define CV_SCR_LIST_TEXT_Y          (CV_SCR_LIST_SPIRTE_Y - (CV_SCR_LIST_SPIRTE_SIZE_Y/2) + 0 )

//Minimum Y value to register touch on the CV screen for scrolling the list
#define CV_SCR_TOUCH_Y_MIN  40

//Defines for the Loco Name text on the CV Screen
#define CV_SCR_LOCONAME_TXT_X   4
#define CV_SCR_LOCONAME_TXT_Y   (BOT_TOPBARHEIGHT + 5)


int testCVListBasePointer = 6;
int cvListSize =  7;
#define CV_LIST_CV_COUNT    512
#define CV_LIST_CV_STRLEN   128
//char testCVList[CV_LIST_CV_COUNT][CV_LIST_CV_STRLEN];
bool canUpScroll = true, canDnScroll = true;
//char testList[] = "Active::1.00::0.00::1.00??TractiveEffort::0.00::-1000.00::1000.00??RPM::600.00::0.00::2400.00??MainReservoirPressureBAR::9.65::0.00::10.00??TrainBrakeCylinderPressureBAR::1.13::0.00::7.00??HandBrake::0.00::0.00::1.00??Headlights::0.00::0.00::2.00??EngineStop::0.00::0.00::1.00??EngineStart::0.00::0.00::1.00??SpeedometerMPH::0.00::0.00::100.00??Regulator::0.00::0.00::1.00??Reverser::0.00::-1.00::1.00??SimpleChangeDirection::1.00::-1.00::1.00??SimpleThrottle::0.28::0.00::1.00??TrainBrakeControl::0.44::0.00::1.00??Wipers::0.00::0.00::1.00??AWS::0.00::0.00::1.00??AWSReset::0.00::0.00::1.00??AWSClearCount::0.00::0.00::2000000000.00??AWSWarnCount::0.00::0.00::1.00??EmergencyBrake::0.00::0.00::1.00??Horn::0.00::0.00::1.00??Startup::1.00::-1.00::1.00??Sander::0.00::0.00::1.00??DoorsOpenCloseLeft::0.00::0.00::1.00??DoorsOpenCloseRight::0.00::0.00::1.00??ThrottleAndBrake::0.25::0.00::1.00??DRAButton::0.00::0.00::1.00??";


//Config Screen

#define CFG_SCR_CFGAREA_SPIRTE_X        204
#define CFG_SCR_CFGAREA_SPIRTE_Y        145
#define CFG_SCR_CFGAREA_SPIRTE_SIZE_X   232
#define CFG_SCR_CFGAREA_SPIRTE_SIZE_Y   190

//First Column

#define CFG_SCR_BUTT_CONTROL_SIZE   38
#define CFG_SCR_BUTT_SPACING        4
#define CFG_SCR_BUTT_SPACINGANDSIZE (4 + CFG_SCR_BUTT_CONTROL_SIZE)
#define CFG_SCR_BUTT_ANIM           2

#define CFG_SCR_BUTT_CPAD_VERT_TOUCH_X  4
#define CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y  30
#define CFG_SCR_BUTT_CPAD_VERT_X        (CFG_SCR_BUTT_CPAD_VERT_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_CPAD_VERT_Y        (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_CPAD_HORI_TOUCH_X  CFG_SCR_BUTT_CPAD_VERT_TOUCH_X
#define CFG_SCR_BUTT_CPAD_HORI_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + CFG_SCR_BUTT_SPACINGANDSIZE)
#define CFG_SCR_BUTT_CPAD_HORI_X        (CFG_SCR_BUTT_CPAD_HORI_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_CPAD_HORI_Y        (CFG_SCR_BUTT_CPAD_HORI_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_DPAD_VERT_TOUCH_X  CFG_SCR_BUTT_CPAD_VERT_TOUCH_X
#define CFG_SCR_BUTT_DPAD_VERT_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_SPACINGANDSIZE*2))
#define CFG_SCR_BUTT_DPAD_VERT_X        (CFG_SCR_BUTT_DPAD_VERT_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_DPAD_VERT_Y        (CFG_SCR_BUTT_DPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_DPAD_HORI_TOUCH_X  CFG_SCR_BUTT_CPAD_VERT_TOUCH_X
#define CFG_SCR_BUTT_DPAD_HORI_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_SPACINGANDSIZE*3))
#define CFG_SCR_BUTT_DPAD_HORI_X        (CFG_SCR_BUTT_DPAD_HORI_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_DPAD_HORI_Y        (CFG_SCR_BUTT_DPAD_HORI_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_L_TOUCH_X  CFG_SCR_BUTT_CPAD_VERT_TOUCH_X
#define CFG_SCR_BUTT_L_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_SPACINGANDSIZE*4))
#define CFG_SCR_BUTT_L_X        (CFG_SCR_BUTT_L_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_L_Y        (CFG_SCR_BUTT_L_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

//Second Column

#define CFG_SCR_BUTT_A_TOUCH_X  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_X + CFG_SCR_BUTT_SPACINGANDSIZE)
#define CFG_SCR_BUTT_A_TOUCH_Y  CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y
#define CFG_SCR_BUTT_A_X        (CFG_SCR_BUTT_A_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_A_Y        (CFG_SCR_BUTT_A_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_B_TOUCH_X  CFG_SCR_BUTT_A_TOUCH_X
#define CFG_SCR_BUTT_B_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_SPACINGANDSIZE))
#define CFG_SCR_BUTT_B_X        (CFG_SCR_BUTT_B_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_B_Y        (CFG_SCR_BUTT_B_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_X_TOUCH_X  CFG_SCR_BUTT_A_TOUCH_X
#define CFG_SCR_BUTT_X_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_SPACINGANDSIZE*2))
#define CFG_SCR_BUTT_X_X        (CFG_SCR_BUTT_X_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_X_Y        (CFG_SCR_BUTT_X_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_Y_TOUCH_X  CFG_SCR_BUTT_A_TOUCH_X
#define CFG_SCR_BUTT_Y_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_SPACINGANDSIZE*3))
#define CFG_SCR_BUTT_Y_X        (CFG_SCR_BUTT_Y_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_Y_Y        (CFG_SCR_BUTT_Y_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))

#define CFG_SCR_BUTT_R_TOUCH_X  CFG_SCR_BUTT_A_TOUCH_X
#define CFG_SCR_BUTT_R_TOUCH_Y  (CFG_SCR_BUTT_CPAD_VERT_TOUCH_Y + (CFG_SCR_BUTT_SPACINGANDSIZE*4))
#define CFG_SCR_BUTT_R_X        (CFG_SCR_BUTT_R_TOUCH_X + (CFG_SCR_BUTT_CONTROL_SIZE/2))
#define CFG_SCR_BUTT_R_Y        (CFG_SCR_BUTT_R_TOUCH_Y + (CFG_SCR_BUTT_CONTROL_SIZE/2))


#define CFG_SCR_AXIS_NAME_TEXT_X    CFG_SCR_CFGAREA_SPIRTE_X
#define CFG_SCR_AXIS_NAME_TEXT_Y    (CFG_SCR_CFGAREA_SPIRTE_Y - (CFG_SCR_CFGAREA_SPIRTE_SIZE_Y /2 ) - 19)

#define CFG_SCR_AXIS_CONFIG_TEXT_X  (CFG_SCR_AXIS_NAME_TEXT_X - (CFG_SCR_CFGAREA_SPIRTE_SIZE_X /2 ) + 20)
#define CFG_SCR_AXIS_CONFIG_TEXT_Y  (CFG_SCR_CFGAREA_SPIRTE_Y - (CFG_SCR_CFGAREA_SPIRTE_SIZE_Y /2 ) + 30)

#define CFG_SCR_TICKBOX_X   (CFG_SCR_CFGAREA_SPIRTE_X + 30)
#define CFG_SCR_TICKBOX_Y   (CFG_SCR_CFGAREA_SPIRTE_Y - 26)
#define CFG_SCR_TICKBOX_SIZE        10
#define CFG_SCR_TICKBOX_SCALE_SIZE  (CFG_SCR_TICKBOX_SIZE*2)
#define CFG_SCR_TICKBOX_TOUCH_X     (CFG_SCR_TICKBOX_X - (CFG_SCR_TICKBOX_SCALE_SIZE/2))
#define CFG_SCR_TICKBOX_TOUCH_Y     (CFG_SCR_TICKBOX_Y - (CFG_SCR_TICKBOX_SCALE_SIZE/2))

#define CFG_SCR_BUTT_SETCV_X        (CFG_SCR_CFGAREA_SPIRTE_X)
#define CFG_SCR_BUTT_SETCV_Y        (CFG_SCR_CFGAREA_SPIRTE_Y + 25)
#define CFG_SCR_BUTT_SETCV_SIZE_X   82
#define CFG_SCR_BUTT_SETCV_SIZE_Y   22
#define CFG_SCR_BUTT_SETCV_TOUCH_X  (CFG_SCR_BUTT_SETCV_X - (CFG_SCR_BUTT_SETCV_SIZE_X/2))
#define CFG_SCR_BUTT_SETCV_TOUCH_Y  (CFG_SCR_BUTT_SETCV_Y - (CFG_SCR_BUTT_SETCV_SIZE_Y/2))



//-------------

//Touch Screen Click Animation

#define TOUCH_SCR_CLICK_ANIM_X  2
#define TOUCH_SCR_CLICK_ANIM_Y  2

//Touch Screen Range

#define TOUCH_SCREEN_ADJ_X  5
#define TOUCH_SCREEN_ADJ_Y  5


//UI Connection State Sprite Position
#define UI_CONSTATE_X	0.96
#define UI_CONSTATE_Y	0.06

#define UI_WIFI_X       18
#define UI_WIFI_Y       13
#define WIFI_LEVEL_0    0
#define WIFI_LEVEL_1    1
#define WIFI_LEVEL_2    2
#define WIFI_LEVEL_3    3

//UI DPad Sprite Position
#define UI_DPAD_X		0.175
#define UI_DPAD_Y		0.75

//UI CPad Sprite Position
#define UI_CPAD_X		0.175
#define UI_CPAD_Y		0.4

//Count of static hardware rendered text strings
#define S_STRING_COUNT	1
//Parameters for rendering the title string
#define STRING_TITLE_S	"3DSTS Controller"
#define STRING_TITLE_Y	7

#define D_STRING_COUNT 1

